### ISSUE TITLE
Per-project Settings & Project-based GOPATH

### ISSUE THREAD

**Issue by holys** [buaazp/Godef#17]
integrate with gosublime 

https://github.com/DisposaBoy/GoSublime/blob/master/USAGE.md#per-project-settings--project-based-gopath

**Comment by javasgl** [comment]
per-project GOPATH config don`t work.
my project settings like this:
```
{
	"settings": {
		"GoSublime": {
			"env": {
				"GOPATH": "/Users/songgl/codes/studygolang",
				"GOROOT": "/usr/local/go"
			}
		}
	}
}
```
but , `Gdef` load failed because of  `no GOPATH defined`
```
===============[Godef]Load Begin==============
[Godef]ERROR: no GOPATH defined
===============[Godef] Load End===============
```

**Comment by holys** [comment]
@javasgl  It's recommended to use vscode instead sublime text.  Vscode has official go plugin which  is powerful and you can have sublime keymap in vscode so you don't need learn new keymap.
