### ISSUE TITLE
no definition found: b'godef 是什么错？

### ISSUE THREAD

**Issue by sheepbao** [buaazp/Godef#19]
按readme里设置了插件的gopat、goroot和快捷键，当我用的时候报这个错：
`=================[Godef]Begin=================
[Godef]INFO: using godef: /home/lstbao/work/listomego/bin/godef
[Godef]INFO: selcet_begin: 134 offset: 134
[Godef]INFO: spawning: /home/lstbao/work/listomego/bin/godef -f /home/lstbao/bao/program/javascript/myPaintOnline/main.go -o 134
[Godef]ERROR: no definition found: b'godef: no declaration found for socketio.NewServer\n'

=================[Godef] End =================
`
配置如下：

` {
      "goroot": "/home/lstbao/software/go",
      "gopath": "/home/lstbao/work/listomego"
  }
  `
sublime版本3103， 系统ubuntu 16.04 64 位

**Comment by sheepbao** [comment]
我知道原因了，是godef的原因，如果引入的包名和包名所对应的文件名不一样就不能正常跳转

**Comment by buaazp** [comment]
对，名字不同的话最好引入的时候自定义一下名字：
```
httpprof "net/http/pprof"
```
